In [124]:
import pandas as pd
import numpy as np

odds_df = pd.read_pickle("odds.pickle")
shutuba_df = pd.read_pickle("shutuba.pickle")

In [125]:
odds_df

人気  枠  馬番   印         馬名  単勝オッズ        複勝オッズ
0    1  8  13 NaN  ノーダブルディップ    3.2    1.2 - 1.8
1    2  5   6 NaN   トーセンダニエル    3.4    1.2 - 1.7
2    3  8  12 NaN    ショベルヘッド    3.5    1.2 - 1.6
3    4  6   8 NaN   インヴァリアンス    7.3    1.7 - 2.6
4    5  7  10 NaN    ロクネンニクミ   18.7    3.3 - 5.5
5    6  1   1 NaN  シゲルセンチュリー   27.6    3.6 - 6.2
6    7  4   4 NaN  カイザーレヴァンテ   43.8    5.1 - 8.9
7    8  7  11 NaN   セイウンスパーダ   57.9    5.0 - 8.6
8    9  3   3 NaN    サノノバーディ   72.8   7.9 - 13.9
9   10  2   2 NaN   ナンヨーノワール   80.4   8.2 - 14.3
10  11  4   5 NaN      アルビレオ  198.1  23.6 - 42.1
11  12  6   9 NaN    マイネルホップ  299.5  22.3 - 39.9
12  13  5   7 NaN       センナリ  489.0  37.7 - 67.4

In [126]:
odds_df.sort_values(by="馬番",ascending=True, inplace=True)
odds_df

人気  枠  馬番   印         馬名  単勝オッズ        複勝オッズ
5    6  1   1 NaN  シゲルセンチュリー   27.6    3.6 - 6.2
9   10  2   2 NaN   ナンヨーノワール   80.4   8.2 - 14.3
8    9  3   3 NaN    サノノバーディ   72.8   7.9 - 13.9
6    7  4   4 NaN  カイザーレヴァンテ   43.8    5.1 - 8.9
10  11  4   5 NaN      アルビレオ  198.1  23.6 - 42.1
1    2  5   6 NaN   トーセンダニエル    3.4    1.2 - 1.7
12  13  5   7 NaN       センナリ  489.0  37.7 - 67.4
3    4  6   8 NaN   インヴァリアンス    7.3    1.7 - 2.6
11  12  6   9 NaN    マイネルホップ  299.5  22.3 - 39.9
4    5  7  10 NaN    ロクネンニクミ   18.7    3.3 - 5.5
7    8  7  11 NaN   セイウンスパーダ   57.9    5.0 - 8.6
2    3  8  12 NaN    ショベルヘッド    3.5    1.2 - 1.6
0    1  8  13 NaN  ノーダブルディップ    3.2    1.2 - 1.8

In [127]:
odds_df

人気  枠  馬番   印         馬名  単勝オッズ        複勝オッズ
5    6  1   1 NaN  シゲルセンチュリー   27.6    3.6 - 6.2
9   10  2   2 NaN   ナンヨーノワール   80.4   8.2 - 14.3
8    9  3   3 NaN    サノノバーディ   72.8   7.9 - 13.9
6    7  4   4 NaN  カイザーレヴァンテ   43.8    5.1 - 8.9
10  11  4   5 NaN      アルビレオ  198.1  23.6 - 42.1
1    2  5   6 NaN   トーセンダニエル    3.4    1.2 - 1.7
12  13  5   7 NaN       センナリ  489.0  37.7 - 67.4
3    4  6   8 NaN   インヴァリアンス    7.3    1.7 - 2.6
11  12  6   9 NaN    マイネルホップ  299.5  22.3 - 39.9
4    5  7  10 NaN    ロクネンニクミ   18.7    3.3 - 5.5
7    8  7  11 NaN   セイウンスパーダ   57.9    5.0 - 8.6
2    3  8  12 NaN    ショベルヘッド    3.5    1.2 - 1.6
0    1  8  13 NaN  ノーダブルディップ    3.2    1.2 - 1.8

## オッズの加工

In [141]:
odds_1 = np.empty(len(odds_df.index))
odds_1to3 = np.empty(len(odds_df.index))
for i in range(len(odds_df.index)):
    odds_1[i] = odds_df["単勝オッズ"].iloc[i]
    odds_1to3[i] = odds_df["複勝オッズ"].str.split(" ",expand=True).iloc[i][0]

In [142]:
shutuba_df

枠  馬番   印         馬名  性齢    斤量     騎手     厩舎  馬体重(増減)    オッズ  人気  登録  メモ
0   1   1  --  シゲルセンチュリー  牝2  54.0    柴田善   美浦石毛  462(+2)   27.6   6 NaN NaN
1   2   2  --   ナンヨーノワール  牡2  55.0    木幡巧   美浦杉浦  448(-2)   80.4  10 NaN NaN
2   3   3  --    サノノバーディ  牡2  55.0     田辺   美浦尾形  456(-2)   72.8   9 NaN NaN
3   4   4  --  カイザーレヴァンテ  牡2  55.0  Ｍデムーロ  美浦田中剛  488(-4)   43.8   7 NaN NaN
4   4   5  --      アルビレオ  牡2  55.0     武藤    美浦林  482(-2)  198.1  11 NaN NaN
5   5   6  --   トーセンダニエル  牡2  55.0    武士沢  美浦古賀史  548(+8)    3.4   2 NaN NaN
6   5   7  --       センナリ  牡2  54.0    木幡育  美浦大江原  482(-4)  489.0  13 NaN NaN
7   6   8  --   インヴァリアンス  牡2  55.0    横山典   美浦尾関  482(+4)    7.3   4 NaN NaN
8   6   9  --    マイネルホップ  牡2  55.0    柴田大  美浦伊藤圭  444(+4)  299.5  12 NaN NaN
9   7  10  --    ロクネンニクミ  牡2  55.0    内田博   美浦小笠   516(0)   18.7   5 NaN NaN
10  7  11  --   セイウンスパーダ  牡2  55.0     大野   美浦栗田  488(+6)   57.9   8 NaN NaN
11  8  12  --    ショベルヘッド  牡2  55.0   ルメール  美浦藤沢和  468(+8)    3.5   3 NaN NaN
12  8  13  --  ノーダブルディップ  牡2  55.0    北村宏  美浦古賀慎  546(+4)    3.2   1 NaN NaN

## 出馬表の加工

In [155]:
def processing_shutubatable(results):
    # results = pd.read_pickle("results.pickle")
    df = results.copy()
    # 着順
    # df = df[~(df["着順"].astype(str).str.contains("\D"))]
    # df["着順"] = df["着順"].astype(int)
    # 性別
    df["性別"] = df["性齢"].map(lambda x: str(x)[0])
    df["性別"] = df["性別"].map({"牡": 1, "牝": 0, "セ": 1})  # 雄:1,牝:0
    # df["性別"]=df["性別"].astype(int)
    # df["性別"] = pd.get_dummies(df["性別"])
    # 年齢
    df["年齢"] = df["性齢"].map(lambda x: str(x)[1:])
    df["年齢"] = df["年齢"].astype(int)
    # 体重
    df = df.rename(columns={'馬体重(増減)': "馬体重"})
    df["体重"] = df["馬体重"].str.split("(", expand=True)[0].astype(int)
    # 体重変化
    df["体重変化"] = df["馬体重"].str.split("(", expand=True)[1].str[:-1].astype(int)
    # 人気と単勝をint型に
    df["人気"] = df["人気"].astype(int)
    # df["単勝"] = df["単勝"].astype(float)
    df = df.rename(columns={'オッズ': "単勝"})
    df = df.rename(columns={'枠': "枠番"})
    #人気順にソート
    df = df.sort_values(by="馬番",ascending=True)
    # いらない列の消去
    df.drop(["印","性齢","馬名", "厩舎", "馬体重", "登録", "メモ","騎手","馬番"], axis=1, inplace=True)

    return df

In [156]:
test = processing_shutubatable(shutuba_df)
test

枠番    斤量     単勝  人気  性別  年齢   体重  体重変化
0    1  54.0   27.6   6   0   2  462     2
1    2  55.0   80.4  10   1   2  448    -2
2    3  55.0   72.8   9   1   2  456    -2
3    4  55.0   43.8   7   1   2  488    -4
4    4  55.0  198.1  11   1   2  482    -2
5    5  55.0    3.4   2   1   2  548     8
6    5  54.0  489.0  13   1   2  482    -4
7    6  55.0    7.3   4   1   2  482     4
8    6  55.0  299.5  12   1   2  444     4
9    7  55.0   18.7   5   1   2  516     0
10   7  55.0   57.9   8   1   2  488     6
11   8  55.0    3.5   3   1   2  468     8
12   8  55.0    3.2   1   1   2  546     4

In [157]:
# モデルの読み込み
import pickle
filename="finalized_model.sav"
model = pickle.load(open(filename, 'rb'))

In [158]:
model.predict_proba(test)

array([[2.06448639e-01, 2.66764006e-01, 2.80585302e-01, 2.46202052e-01],
       [6.39953427e-02, 1.44667998e-01, 2.26031758e-01, 5.65304901e-01],
       [8.61430694e-02, 1.70978633e-01, 2.50338687e-01, 4.92539610e-01],
       [1.64185459e-01, 2.32710384e-01, 2.87067485e-01, 3.16036672e-01],
       [1.23186282e-02, 4.78987023e-02, 1.12260452e-01, 8.27522217e-01],
       [3.86379072e-01, 2.95648983e-01, 2.36068019e-01, 8.19039257e-02],
       [9.99572489e-05, 1.53882937e-03, 9.39229333e-03, 9.88968920e-01],
       [3.02668418e-01, 2.91841346e-01, 2.71825259e-01, 1.33664978e-01],
       [2.17209996e-03, 1.48136603e-02, 4.85862233e-02, 9.34428017e-01],
       [2.60670013e-01, 2.74173909e-01, 2.86032615e-01, 1.79123463e-01],
       [1.22212206e-01, 2.07262866e-01, 2.76212110e-01, 3.94312818e-01],
       [3.36049868e-01, 2.98611183e-01, 2.61654491e-01, 1.03684458e-01],
       [4.20002010e-01, 2.87004200e-01, 2.28692291e-01, 6.43014991e-02]])

In [159]:
# 予想
model.predict(test)

array([3, 4, 4, 4, 4, 1, 4, 1, 4, 3, 4, 1, 1], dtype=int64)

In [160]:
# 係数保存
# import numpy as np
coef = np.empty((len(test.index),4))
for i in range(len(test.index)):
    for t in range(4):
        coef[i][t] = model.predict_proba(test)[i][t]

In [161]:
coef

array([[2.06448639e-01, 2.66764006e-01, 2.80585302e-01, 2.46202052e-01],
       [6.39953427e-02, 1.44667998e-01, 2.26031758e-01, 5.65304901e-01],
       [8.61430694e-02, 1.70978633e-01, 2.50338687e-01, 4.92539610e-01],
       [1.64185459e-01, 2.32710384e-01, 2.87067485e-01, 3.16036672e-01],
       [1.23186282e-02, 4.78987023e-02, 1.12260452e-01, 8.27522217e-01],
       [3.86379072e-01, 2.95648983e-01, 2.36068019e-01, 8.19039257e-02],
       [9.99572489e-05, 1.53882937e-03, 9.39229333e-03, 9.88968920e-01],
       [3.02668418e-01, 2.91841346e-01, 2.71825259e-01, 1.33664978e-01],
       [2.17209996e-03, 1.48136603e-02, 4.85862233e-02, 9.34428017e-01],
       [2.60670013e-01, 2.74173909e-01, 2.86032615e-01, 1.79123463e-01],
       [1.22212206e-01, 2.07262866e-01, 2.76212110e-01, 3.94312818e-01],
       [3.36049868e-01, 2.98611183e-01, 2.61654491e-01, 1.03684458e-01],
       [4.20002010e-01, 2.87004200e-01, 2.28692291e-01, 6.43014991e-02]])

## ソルバー

In [162]:
w = coef[:,0]
w
v = coef[:,0] + coef[:,1] + coef[:,2]
v

array([0.75379795, 0.4346951 , 0.50746039, 0.68396333, 0.17247778,
       0.91809607, 0.01103108, 0.86633502, 0.06557198, 0.82087654,
       0.60568718, 0.89631554, 0.9356985 ])

In [163]:
from pulp import *

Max_Money = 10000  # 持ち金
# 1位になる確率
# w = [0.4, 0.3, 0.2]
# 3位以内になる確率
# v = [0.5, 0.4, 0.5]

# 数理モデル
m = pulp.LpProblem(sense=LpMaximize)
# 変数
r = range(len(w))
# x = [pulp.LpVariable('x_{}'.format(i), cat=LpBinary) for i in r]
x = [pulp.LpVariable('x%d' % i, lowBound=0, cat=LpInteger) for i in r]
y = [pulp.LpVariable('y%d' % i, lowBound=0, cat=LpInteger) for i in r]

# 目的関数
# m += pulp.lpDot(w, x, odds_1) + pulp.lpDot(v, y, odds_1to3)
m += pulp.lpSum(w[i] * x[i] * odds_1[i] + v[i] * y[i] * odds_1to3[i] for i in range(len(shutuba_df.index)))
# m += pulp.lpSum([w[i], v[i]], [x[i], y[i]] for i in r)
# 制約条件
m += pulp.lpSum(x) + pulp.lpSum(y) <= Max_Money
# 最適化計算
m.solve()
# 出力
print("[単勝]")
for i in r:
    print('番号:{} 掛け金:{}'.format(i+1, value(x[i])))
print("[複勝]")
for i in r:
    print('番号:{} 掛け金:{}'.format(i+1, value(y[i])))
print('\n目的関数:{}'.format(value(m.objective)))

[単勝]
番号:1 掛け金:0
番号:2 掛け金:0
番号:3 掛け金:0
番号:4 掛け金:10000
番号:5 掛け金:0
番号:6 掛け金:0
番号:7 掛け金:0
番号:8 掛け金:0
番号:9 掛け金:0
番号:10 掛け金:0
番号:11 掛け金:0
番号:12 掛け金:0
番号:13 掛け金:0
[複勝]
番号:1 掛け金:0
番号:2 掛け金:0
番号:3 掛け金:0
番号:4 掛け金:0
番号:5 掛け金:0
番号:6 掛け金:0
番号:7 掛け金:0
番号:8 掛け金:0
番号:9 掛け金:0
番号:10 掛け金:0
番号:11 掛け金:0
番号:12 掛け金:0
番号:13 掛け金:0

目的関数:71913.2311912012


In [164]:
odds_1to3

array([ 3.6,  8.2,  7.9,  5.1, 23.6,  1.2, 37.7,  1.7, 22.3,  3.3,  5. ,
        1.2,  1.2])